### ISSUE TITLE
Back button doesn't take you to homepage when selecting fire category in report hazard section

### ISSUE THREAD

**Issue by ReinhardtBotha** [whamester/WMDD-4885-Project#106]
![ezgif-2-a56c3420c8](https://github.com/whamester/WMDD-4885-Project/assets/89278135/f05a9c75-b234-4072-8aa2-e153ba38f93e)

**Comment by whamester** [comment]
https://github.com/whamester/WMDD-4885-Project/assets/57273227/ab36fa7d-435d-4dd0-8325-542a14d8c6f0
