### ISSUE TITLE
When user tries to report a fire hazard, they cannot reach the review section

### ISSUE THREAD

**Issue by ALFAROSO** [whamester/WMDD-4885-Project#113]
![image](https://github.com/whamester/WMDD-4885-Project/assets/87240930/c00bf0ce-1c11-431e-91c7-71e667e5e317)

**Comment by whamester** [comment]
https://github.com/whamester/WMDD-4885-Project/assets/57273227/cacceccf-e4f3-4f10-9dcb-b884463d0d37
