### ISSUE TITLE
Add sorting to categories

### ISSUE THREAD

**Issue by whamester** [whamester/WMDD-4885-Project#136]
![image](https://github.com/whamester/WMDD-4885-Project/assets/57273227/968fe05a-42fd-49f6-8100-a02ae9b1964e)

**Comment by whamester** [comment]
<img width="482" alt="Screenshot 2023-11-24 at 6 05 41 PM" src="https://github.com/whamester/WMDD-4885-Project/assets/57273227/65da6a93-323d-4fa4-85b0-ec17d489e741">

https://outsafebc.ca/pages/home/

**Comment by poojachauhan001** [comment]
Approved 👍🏻
