### ISSUE TITLE
Keep the same list of filter tabs as we have in the UI Design File

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#150]
[https://www.figma.com/file/EFlGK158VL4Cphasesw2aS/UI-Design?type=design&node-id=594%3A5755&mode=design&t=KZYZvQAGA9VncK2p-1](url)

**Comment by poojachauhan001** [comment]
![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/c6b366af-beab-4878-a150-620ef58bfef4)

**Comment by whamester** [comment]
Same as: https://github.com/whamester/WMDD-4885-Project/issues/136
