### ISSUE TITLE
[Home] Add a black outline and make the vertical typing bar orange

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#151]
[https://www.figma.com/file/MvZcmP4hpG0PCqjjb8Bk3k/Branding?type=design&node-id=72%3A25&mode=design&t=FQTCoMIYwrzRzJnP-1](url)

**Comment by poojachauhan001** [comment]
![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/6908768e-8b2e-408f-90eb-de0130b5b128)

**Comment by whamester** [comment]
Pull Request: https://github.com/whamester/WMDD-4885-Project/pull/230
