### ISSUE TITLE
Primary button should have a border radius of 0.75rem (currently it is 0.5rem)

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#153]

**Comment by poojachauhan001** [comment]
![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/5b466673-222b-478d-a694-5e9ac4d081b9)

**Comment by ALFAROSO** [comment]
r4r https://github.com/whamester/WMDD-4885-Project/pull/177
