### ISSUE TITLE
Have the same type of outline for the green coloured success toast message as we have for the offline warning message

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#157]
I have added a success and error message state in the branding file for reference.

https://www.figma.com/file/MvZcmP4hpG0PCqjjb8Bk3k/Branding?type=design&node-id=72%3A25&mode=design&t=FQTCoMIYwrzRzJnP-1

**Comment by poojachauhan001** [comment]
![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/02829cb6-63b5-4046-a422-045a31acfce1)

**Comment by whamester** [comment]
How to test: https://github.com/whamester/WMDD-4885-Project/pull/181#issuecomment-1827314263
