### ISSUE TITLE
Need to center align the label and fields in Review Report screen

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#162]
![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/66c3f2f2-eaec-48a6-88b3-452731b67272)

![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/95c01a69-85e0-47ee-add9-fc145f2abf4a)

**Comment by poojachauhan001** [comment]
Also, the labels need to be "medium" instead of "semi-bold"

**Comment by whamester** [comment]
vertically align center
