### ISSUE TITLE
Filter card to hazard card switch issue

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#165]
If I have the filters opened up and I click on any hazard pin, ideally the hazard card should replace the opened filters card. But currently, the filter card remains there and the hazard detail card goes behind it making things overlapped. 

![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/a1582e85-3a49-4e4d-9bf2-4ac7792c43ff)

**Comment by whamester** [comment]
Ready for review on this link: https://outsafebc.ca/

**Comment by poojachauhan001** [comment]
Approved!
