### ISSUE TITLE
One-liner text for Plants Hazard Option needs to be updated

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#168]
![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/b0c5180b-e726-4ed5-83b2-3bbb5c16e001)

**Comment by ALFAROSO** [comment]
![image](https://github.com/whamester/WMDD-4885-Project/assets/87240930/7969d8a6-e494-40d9-b3ac-9c1d7b19880f)

**Comment by poojachauhan001** [comment]
Approved
