### ISSUE TITLE
Report is getting marked as fake automatically

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#169]
I just added a plant hazard report and didn't choose any of the 3 button options. Still, the hazard card shows that I have flagged this report as fake. (even though I didn't).

![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/fd38ea05-a351-48c8-b1b3-d489666c723b)

**Comment by whamester** [comment]
PR:
https://github.com/whamester/WMDD-4885-Project/pull/232
