### ISSUE TITLE
Addition to issue #169 - User shouldn't have the "report as fake" button option for the report they themself added.

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#170]
https://github.com/whamester/WMDD-4885-Project/issues/169#issue-2010441868

![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/15920b9f-c2b6-447d-83f2-5c078157ee27)

**Comment by whamester** [comment]
PR: https://github.com/whamester/WMDD-4885-Project/pull/232
