### ISSUE TITLE
User should not have "Flag Report" button for the reports they added.

### ISSUE THREAD

**Issue by poojachauhan001** [whamester/WMDD-4885-Project#186]
![image](https://github.com/whamester/WMDD-4885-Project/assets/144421139/eac7b3a5-493f-4434-8162-984d2de0e09e)

**Comment by whamester** [comment]
<img width="504" alt="Screenshot 2023-12-08 at 12 42 29 PM" src="https://github.com/whamester/WMDD-4885-Project/assets/57273227/4daefb7d-2fbe-427f-a382-0185419661a5">
<img width="499" alt="Screenshot 2023-12-08 at 12 43 46 PM" src="https://github.com/whamester/WMDD-4885-Project/assets/57273227/2223ded7-85eb-47a8-acf5-88a0f71f804e">

@poojachauhan001  I couldn't replicate this issue, could you verify if it's still happening on your end?
