### ISSUE TITLE
Map not loading when you want to submit a hazard in desktop view

### ISSUE THREAD

**Issue by ReinhardtBotha** [whamester/WMDD-4885-Project#75]
![ezgif-4-ffd2850d90](https://github.com/whamester/WMDD-4885-Project/assets/89278135/2414c2cf-7579-4bdb-ac9e-ff316e475b4c)

**Comment by whamester** [comment]
Uploading Screen Recording 2023-11-07 at 9.13.41 PM.mov…

Fixed
