### ISSUE TITLE
View hazards : Add a friendly message.

### ISSUE THREAD

**Issue by whamester** [whamester/WMDD-4885-Project#90]
![image](https://github.com/whamester/WMDD-4885-Project/assets/57273227/9de6ba12-983f-4127-83d7-c3da019d7144)

Add a friendly message here.

_Originally posted by @whamester in https://github.com/whamester/WMDD-4885-Project/issues/67#issuecomment-1793858636_

**Comment by ReinhardtBotha** [comment]
use a warning alert rather
